# Generated by Django 2.1.1 on 2018-09-02 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_data_api', '0002_auto_20180901_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankbranch',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='bankbranch',
            name='branch',
        ),
        migrations.DeleteModel(
            name='BankBranch',
        ),
    ]
